name: 'Kimchima CI 🚀'
on:
  pull_request:
    branches:
      - 'main'

jobs:
  code_quality:
    name: 'Code Quality 📦'
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
        poetry-version: ["1.8.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install ruff
        run: |
          pip install ruff==0.3.5
      - name: Run linters
        run: |
           make lint


  unittest:
    name: 'Unittest 🔬'
    needs: [code_quality]
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
        poetry-version: ["1.8.2"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run:  |
          make install-dev
      - name: Install PyTest
        run: |
          pip install pytest==8.2.2
      - name: Run tests
        run: |
           make test
